name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build web-app
        run: |
          npm install
          npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        env: 
            REACT_APP_EMAILJS_SERVICE_ID: ${{ env.REACT_APP_EMAILJS_SERVICE_ID }}
            REACT_APP_EMAILJS_TEMPLATE_ID: ${{ env.REACT_APP_EMAILJS_TEMPLATE_ID }}
            REACT_APP_EMAILJS_USER_ID: ${{ env.REACT_APP_EMAILJS_USER_ID }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build